# Generated by Django 4.2.30 on 2026-06-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(help_text='Date of the event')),
                ('location', models.CharField(default='School Campus', max_length=200)),
                ('thumbnail', models.ImageField(help_text='Event cover photo', upload_to='events/')),
            ],
            options={
                'verbose_name': 'School Event',
                'verbose_name_plural': 'School Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(choices=[('book', 'Library / Reading Room'), ('microscope', 'Science Labs (Physics/Chemistry/Biology)'), ('desktop', 'Computer & IT Lab'), ('volleyball', 'Sports Complex & Playground'), ('bus', 'Safe School Transport'), ('music', 'Music, Dance & Art Studio'), ('heartbeat', 'Infirmary / Health Clinic'), ('chalkboard-teacher', 'Smart Classrooms')], default='book', help_text='Select a pre-configured icon to represent this facility', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Detail photo of the facility', null=True, upload_to='facilities/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'School Facility',
                'verbose_name_plural': 'School Facilities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="Used for URL filtering (e.g. 'sports-day')", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Primary heading on the slider', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Secondary descriptive subtitle', max_length=200, null=True)),
                ('image', models.ImageField(help_text='High resolution background image (Recommended 1920x800px)', upload_to='slider/')),
                ('action_text', models.CharField(default='Explore More', help_text='Text shown on the call-to-action button', max_length=50)),
                ('action_url', models.CharField(default='#', help_text='URL or section ID that button points to', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Determines the display order (lower values show first)')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility on website')),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Notice content details', null=True)),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF or document download', null=True, upload_to='notices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_urgent', models.BooleanField(default=False, help_text='Displays with an urgent badge and floats to top')),
            ],
            options={
                'verbose_name': 'Notice / Announcement',
                'verbose_name_plural': 'Notices & Announcements',
                'ordering': ['-is_urgent', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Vyas Public School', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Best size: 200x60px (PNG with transparency)', null=True, upload_to='school/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('email', models.EmailField(default='info@vyaspublicschool.com', max_length=254)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('address', models.TextField(default='Vyas Public School, Campus Area, City, State, India')),
                ('map_embed_url', models.TextField(blank=True, help_text='Google Maps Embed iframe src URL. Extract the src attribute from the Google Maps share embed code.', null=True)),
                ('principal_name', models.CharField(default='Dr. R. K. Vyas', max_length=100)),
                ('principal_title', models.CharField(default="Principal's Message", max_length=100)),
                ('principal_message', models.TextField(default='Welcome to Vyas Public School. We are dedicated to fostering academic excellence and character building. Our goal is to prepare students to face global challenges with confidence and integrity.')),
                ('principal_photo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('stat_students', models.IntegerField(default=1200, verbose_name='Number of Students')),
                ('stat_teachers', models.IntegerField(default=80, verbose_name='Number of Teachers')),
                ('stat_labs', models.IntegerField(default=5, verbose_name='Number of Labs')),
                ('stat_experience', models.IntegerField(default=25, verbose_name='Years of Excellence')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('vision', models.TextField(default='To empower students to become life-long learners and productive members of a dynamic global society.')),
                ('mission', models.TextField(default='To provide a nurturing environment that fosters academic excellence, innovation, collaborative learning, and ethical values.')),
            ],
            options={
                'verbose_name': 'School Configuration',
                'verbose_name_plural': 'School Configuration',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(help_text='e.g. TGT Science, HOD Mathematics, Principal', max_length=100)),
                ('qualification', models.CharField(help_text='e.g. M.Sc. B.Ed.', max_length=150)),
                ('photo', models.ImageField(help_text='Professional headshot of the teacher', upload_to='teachers/')),
                ('order', models.IntegerField(default=0, help_text='Order in staff list')),
            ],
            options={
                'verbose_name': 'Teacher / Staff Member',
                'verbose_name_plural': 'Teachers & Staff',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload high resolution photo', upload_to='gallery/')),
                ('caption', models.CharField(blank=True, help_text='Brief description/tag for the photo', max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='school.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
