# Generated by Django 4.2.30 on 2026-06-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='director_message',
            field=models.TextField(default='Education is not just about academic achievement but about shaping character and building futures. At Vyas Public School, we strive to create an environment where every child can discover their potential and develop into confident, responsible individuals.'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='director_name',
            field=models.CharField(default='Mr. Sanjay Vyas', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='director_photo',
            field=models.ImageField(blank=True, null=True, upload_to='school/'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='director_title',
            field=models.CharField(default="Director's Message", max_length=100),
        ),
    ]
